"""Conservative CleanWin candidate collectors."""

from __future__ import annotations

import os
import fnmatch
from collections.abc import Iterable
from datetime import datetime, timezone
from pathlib import Path

from cleanwincli.identity import capture_filesystem_identity
from cleanwincli.models import Candidate, Finding
from cleanwincli.protection import validate_filesystem_candidate
from cleanwincli.protection_data import DEFAULT_SAFE_CATEGORIES, READ_ONLY_CATEGORIES


DEV_CACHE_RULES: tuple[dict[str, str], ...] = (
    {
        "rule_id": "dev-cache.pip.cache",
        "owner": "pip",
        "env_key": "PIP_CACHE_DIR",
        "default": "local:pip/Cache",
        "official_cleanup_command": "python -m pip cache purge",
        "rationale": "pip HTTP and wheel cache entries are package artifacts that can be regenerated by future installs.",
    },
    {
        "rule_id": "dev-cache.npm.cache",
        "owner": "npm",
        "env_key": "NPM_CONFIG_CACHE",
        "default": "local:npm-cache",
        "official_cleanup_command": "npm cache clean --force",
        "rationale": "npm content-addressed cache entries are verified package artifacts that can be regenerated by npm.",
    },
    {
        "rule_id": "dev-cache.yarn.cache",
        "owner": "Yarn",
        "env_key": "YARN_CACHE_FOLDER",
        "default": "home:.cache/yarn",
        "official_cleanup_command": "yarn cache clean",
        "rationale": "Yarn package cache entries are downloaded dependencies that can be regenerated by Yarn.",
    },
    {
        "rule_id": "dev-cache.pnpm.store",
        "owner": "pnpm",
        "env_key": "PNPM_STORE_PATH",
        "default": "local:pnpm/store",
        "official_cleanup_command": "pnpm store prune",
        "rationale": "pnpm store entries are dependency artifacts; unused content can be regenerated from lockfiles and registries.",
    },
    {
        "rule_id": "dev-cache.nuget.packages",
        "owner": "NuGet",
        "env_key": "NUGET_PACKAGES",
        "default": "home:.nuget/packages",
        "official_cleanup_command": "dotnet nuget locals all --clear",
        "rationale": "NuGet global package cache entries are restore artifacts that can be regenerated by dotnet restore.",
    },
    {
        "rule_id": "dev-cache.cargo.registry",
        "owner": "Cargo",
        "env_key": "CARGO_HOME",
        "default": "home:.cargo/registry/cache",
        "official_cleanup_command": "cargo cache --autoclean (requires cargo-cache)",
        "rationale": "Cargo registry cache entries are crate download artifacts that can be regenerated by Cargo.",
    },
    {
        "rule_id": "dev-cache.go-build.cache",
        "owner": "Go build cache",
        "env_key": "GOCACHE",
        "default": "local:go-build",
        "official_cleanup_command": "go clean -cache",
        "rationale": "Go build cache entries are compiled artifacts that can be regenerated by the Go toolchain.",
    },
    {
        "rule_id": "dev-cache.go-module.cache",
        "owner": "Go module cache",
        "env_key": "GOMODCACHE",
        "default": "home:go/pkg/mod/cache/download",
        "official_cleanup_command": "go clean -modcache",
        "rationale": "Go module cache entries are downloaded module artifacts that can be regenerated by the Go toolchain.",
    },
    {
        "rule_id": "dev-cache.gradle.caches",
        "owner": "Gradle",
        "env_key": "GRADLE_USER_HOME",
        "default": "home:.gradle/caches",
        "official_cleanup_command": "gradle --stop; remove selected caches after review",
        "rationale": "Gradle cache entries are dependency and build artifacts that can be regenerated by Gradle builds.",
    },
    {
        "rule_id": "dev-cache.maven.repository",
        "owner": "Maven",
        "env_key": "MAVEN_REPOSITORY",
        "default": "home:.m2/repository",
        "official_cleanup_command": "mvn dependency:purge-local-repository",
        "rationale": "Maven local repository artifacts can be regenerated from declared dependencies and remote repositories.",
    },
)


PACKAGE_CACHE_RULES: tuple[dict[str, str], ...] = (
    {
        "rule_id": "package-cache.winget.packages",
        "owner": "WinGet",
        "default": "local:Microsoft/WinGet/Packages",
        "official_cleanup_command": "winget source reset --force or remove stale installer payloads only after review",
        "rationale": "WinGet package download payloads are installer artifacts that can be re-downloaded by winget.",
    },
    {
        "rule_id": "package-cache.scoop.cache",
        "owner": "Scoop",
        "default": "home:scoop/cache",
        "official_cleanup_command": "scoop cleanup *",
        "rationale": "Scoop cache entries are downloaded package archives that can be fetched again by Scoop.",
    },
    {
        "rule_id": "package-cache.chocolatey.lib-bad",
        "owner": "Chocolatey",
        "default": "programdata:chocolatey/lib-bad",
        "official_cleanup_command": "choco clean --yes or remove failed package payloads after review",
        "rationale": "Chocolatey lib-bad entries are failed or partial package artifacts that can be recreated by reinstall attempts.",
    },
    {
        "rule_id": "package-cache.chocolatey.cache",
        "owner": "Chocolatey",
        "default": "programdata:chocolatey/cache",
        "official_cleanup_command": "choco clean --yes",
        "rationale": "Chocolatey cache entries are downloaded package payloads that can be fetched again by Chocolatey.",
    },
    {
        "rule_id": "package-cache.uv.cache",
        "owner": "uv",
        "default": "local:uv/cache",
        "official_cleanup_command": "uv cache clean",
        "rationale": "uv cache entries are Python package artifacts and wheels that can be regenerated by uv.",
    },
)


BROWSER_CACHE_RULES: tuple[dict[str, str], ...] = (
    {
        "rule_id": "browser-cache.chrome.default.cache",
        "owner": "Google Chrome",
        "default": "local:Google/Chrome/User Data/Default/Cache",
        "official_cleanup_command": "Use Chrome > Clear browsing data and clear cached images/files only.",
        "rationale": "Chrome Cache directory stores temporary web resources separate from Cookies, Login Data, and profile databases.",
    },
    {
        "rule_id": "browser-cache.edge.profile1.code-cache",
        "owner": "Microsoft Edge",
        "default": "local:Microsoft/Edge/User Data/Profile 1/Code Cache",
        "official_cleanup_command": "Use Edge > Clear browsing data and clear cached images/files only.",
        "rationale": "Edge Code Cache stores regenerated script cache data and does not contain the primary cookie/session database.",
    },
    {
        "rule_id": "browser-cache.firefox.profiles2.cache2",
        "owner": "Mozilla Firefox",
        "default": "local:Mozilla/Firefox/Profiles/default-release/cache2",
        "official_cleanup_command": "Use Firefox > Clear recent history and clear cache only.",
        "rationale": "Firefox cache2 stores temporary browser cache entries that can be rebuilt from future browsing.",
    },
)

BROWSER_PROFILE_CACHE_RULES: dict[str, dict[str, str]] = {
    "chrome-cache": {
        "rule_id": "browser-cache.chrome.cache",
        "owner": "Google Chrome",
        "official_cleanup_command": "Use Chrome > Clear browsing data and clear cached images/files only.",
        "rationale": "Chrome Cache directories store temporary web resources separate from Cookies, Login Data, and profile databases.",
    },
    "chrome-code-cache": {
        "rule_id": "browser-cache.chrome.code-cache",
        "owner": "Google Chrome",
        "official_cleanup_command": "Use Chrome > Clear browsing data and clear cached images/files only.",
        "rationale": "Chrome Code Cache stores regenerated script cache data and does not contain the primary cookie/session database.",
    },
    "edge-cache": {
        "rule_id": "browser-cache.edge.cache",
        "owner": "Microsoft Edge",
        "official_cleanup_command": "Use Edge > Clear browsing data and clear cached images/files only.",
        "rationale": "Edge Cache directories store temporary web resources separate from Cookies, Login Data, and profile databases.",
    },
    "edge-code-cache": {
        "rule_id": "browser-cache.edge.code-cache",
        "owner": "Microsoft Edge",
        "official_cleanup_command": "Use Edge > Clear browsing data and clear cached images/files only.",
        "rationale": "Edge Code Cache stores regenerated script cache data and does not contain the primary cookie/session database.",
    },
    "firefox-cache2": {
        "rule_id": "browser-cache.firefox.cache2",
        "owner": "Mozilla Firefox",
        "official_cleanup_command": "Use Firefox > Clear recent history and clear cache only.",
        "rationale": "Firefox cache2 directories store temporary browser cache entries that can be rebuilt from future browsing.",
    },
}

APP_LEFTOVER_RULES: tuple[dict[str, object], ...] = (
    {
        "rule_id": "app-leftovers.slack.cache",
        "owner": "Slack",
        "default": "roaming:Slack/Cache",
        "active_markers": ("local:slack/slack.exe", "programfiles:Slack/slack.exe", "programfilesx86:Slack/slack.exe"),
        "official_cleanup_command": "Uninstall Slack from Settings > Apps, then remove reviewed Slack cache/log leftovers.",
        "rationale": "Slack Cache contains regenerated Electron web cache left behind after uninstall and does not include primary workspace credentials.",
    },
    {
        "rule_id": "app-leftovers.slack.gpu-cache",
        "owner": "Slack",
        "default": "roaming:Slack/GPUCache",
        "active_markers": ("local:slack/slack.exe", "programfiles:Slack/slack.exe", "programfilesx86:Slack/slack.exe"),
        "official_cleanup_command": "Uninstall Slack from Settings > Apps, then remove reviewed Slack cache/log leftovers.",
        "rationale": "Slack GPUCache contains regenerated renderer artifacts left behind after uninstall.",
    },
    {
        "rule_id": "app-leftovers.teams-classic.logs",
        "owner": "Microsoft Teams classic",
        "default": "roaming:Microsoft/Teams/logs",
        "active_markers": ("local:Microsoft/Teams/current/Teams.exe", "programfiles:Microsoft/Teams/current/Teams.exe", "programfilesx86:Microsoft/Teams/current/Teams.exe"),
        "official_cleanup_command": "Uninstall Microsoft Teams classic from Settings > Apps, then remove reviewed Teams log/cache leftovers.",
        "rationale": "Teams classic logs are diagnostic text artifacts that may remain after uninstall and can be regenerated by a future install.",
    },
    {
        "rule_id": "app-leftovers.teams-classic.cache",
        "owner": "Microsoft Teams classic",
        "default": "roaming:Microsoft/Teams/Cache",
        "active_markers": ("local:Microsoft/Teams/current/Teams.exe", "programfiles:Microsoft/Teams/current/Teams.exe", "programfilesx86:Microsoft/Teams/current/Teams.exe"),
        "official_cleanup_command": "Uninstall Microsoft Teams classic from Settings > Apps, then remove reviewed Teams log/cache leftovers.",
        "rationale": "Teams classic Cache contains regenerated Electron cache entries left behind after uninstall.",
    },
    {
        "rule_id": "app-leftovers.discord.cache",
        "owner": "Discord",
        "default": "roaming:discord/Cache",
        "active_markers": ("local:Discord/Update.exe", "local:Discord/app-*/Discord.exe"),
        "official_cleanup_command": "Uninstall Discord from Settings > Apps, then remove reviewed Discord cache leftovers.",
        "rationale": "Discord Cache contains regenerated Electron web cache artifacts left behind after uninstall.",
    },
    {
        "rule_id": "app-leftovers.zoom.logs",
        "owner": "Zoom",
        "default": "roaming:Zoom/logs",
        "active_markers": ("roaming:Zoom/bin/Zoom.exe", "programfiles:Zoom/bin/Zoom.exe", "programfilesx86:Zoom/bin/Zoom.exe"),
        "official_cleanup_command": "Uninstall Zoom from Settings > Apps, then remove reviewed Zoom logs.",
        "rationale": "Zoom logs are diagnostic artifacts that can remain after uninstall and are not user documents.",
    },
    {
        "rule_id": "app-leftovers.vscode.cached-data",
        "owner": "Visual Studio Code",
        "default": "roaming:Code/CachedData",
        "active_markers": ("local:Programs/Microsoft VS Code/Code.exe", "programfiles:Microsoft VS Code/Code.exe", "programfilesx86:Microsoft VS Code/Code.exe"),
        "official_cleanup_command": "Uninstall Visual Studio Code from Settings > Apps, then remove reviewed Code cache/log leftovers.",
        "rationale": "VS Code CachedData contains regenerated extension host and workbench cache artifacts, not user projects or settings.",
    },
    {
        "rule_id": "app-leftovers.vscode.logs",
        "owner": "Visual Studio Code",
        "default": "roaming:Code/logs",
        "active_markers": ("local:Programs/Microsoft VS Code/Code.exe", "programfiles:Microsoft VS Code/Code.exe", "programfilesx86:Microsoft VS Code/Code.exe"),
        "official_cleanup_command": "Uninstall Visual Studio Code from Settings > Apps, then remove reviewed Code cache/log leftovers.",
        "rationale": "VS Code logs are diagnostic artifacts left behind after uninstall and do not include workspace source files.",
    },
    {
        "rule_id": "app-leftovers.jetbrains.logs",
        "owner": "JetBrains IDEs",
        "default": "local:JetBrains/*/log",
        "active_markers": ("local:JetBrains/Toolbox/bin/jetbrains-toolbox.exe", "programfiles:JetBrains/*/bin/*.exe", "programfilesx86:JetBrains/*/bin/*.exe"),
        "official_cleanup_command": "Uninstall JetBrains IDEs or Toolbox, then remove reviewed IDE log/cache leftovers.",
        "rationale": "JetBrains log directories contain IDE diagnostics and can remain after uninstall without containing project source code.",
    },
    {
        "rule_id": "app-leftovers.docker-desktop.logs",
        "owner": "Docker Desktop",
        "default": "local:Docker/log",
        "active_markers": ("programfiles:Docker/Docker/Docker Desktop.exe", "local:Docker Desktop/Docker Desktop.exe"),
        "official_cleanup_command": "Uninstall Docker Desktop, then remove logs only after confirming WSL data and volumes are not targeted.",
        "rationale": "Docker Desktop log leftovers are diagnostic files; volumes, images, and WSL disk images remain excluded by policy.",
    },
    {
        "rule_id": "app-leftovers.postman.cache",
        "owner": "Postman",
        "default": "roaming:Postman/Cache",
        "active_markers": ("local:Postman/Postman.exe", "local:Programs/Postman/Postman.exe"),
        "official_cleanup_command": "Uninstall Postman from Settings > Apps, then remove reviewed Postman cache/log leftovers.",
        "rationale": "Postman Cache contains regenerated Electron web cache artifacts; workspace data and account state remain outside this rule.",
    },
    {
        "rule_id": "app-leftovers.postman.logs",
        "owner": "Postman",
        "default": "roaming:Postman/logs",
        "active_markers": ("local:Postman/Postman.exe", "local:Programs/Postman/Postman.exe"),
        "official_cleanup_command": "Uninstall Postman from Settings > Apps, then remove reviewed Postman cache/log leftovers.",
        "rationale": "Postman logs are diagnostic leftovers that do not include exported collections or user documents.",
    },
    {
        "rule_id": "app-leftovers.notion.cache",
        "owner": "Notion",
        "default": "roaming:Notion/Cache",
        "active_markers": ("local:Programs/Notion/Notion.exe", "local:Notion/Notion.exe"),
        "official_cleanup_command": "Uninstall Notion from Settings > Apps, then remove reviewed Notion cache/log leftovers.",
        "rationale": "Notion Cache contains regenerated Electron web cache artifacts; exported pages and user documents remain outside this rule.",
    },
    {
        "rule_id": "app-leftovers.notion.logs",
        "owner": "Notion",
        "default": "roaming:Notion/logs",
        "active_markers": ("local:Programs/Notion/Notion.exe", "local:Notion/Notion.exe"),
        "official_cleanup_command": "Uninstall Notion from Settings > Apps, then remove reviewed Notion cache/log leftovers.",
        "rationale": "Notion logs are diagnostic leftovers and can be removed after uninstall review.",
    },
    {
        "rule_id": "app-leftovers.figma.cache",
        "owner": "Figma",
        "default": "roaming:Figma/Cache",
        "active_markers": ("local:Figma/Figma.exe", "local:Programs/Figma/Figma.exe"),
        "official_cleanup_command": "Uninstall Figma from Settings > Apps, then remove reviewed Figma cache/log leftovers.",
        "rationale": "Figma Cache contains regenerated Electron cache artifacts; cloud design files and exports remain outside this rule.",
    },
    {
        "rule_id": "app-leftovers.figma.logs",
        "owner": "Figma",
        "default": "roaming:Figma/logs",
        "active_markers": ("local:Figma/Figma.exe", "local:Programs/Figma/Figma.exe"),
        "official_cleanup_command": "Uninstall Figma from Settings > Apps, then remove reviewed Figma cache/log leftovers.",
        "rationale": "Figma logs are diagnostic leftovers that can be regenerated by future installs.",
    },
    {
        "rule_id": "app-leftovers.obs-studio.logs",
        "owner": "OBS Studio",
        "default": "roaming:obs-studio/logs",
        "active_markers": ("programfiles:obs-studio/bin/64bit/obs64.exe", "programfilesx86:obs-studio/bin/64bit/obs64.exe"),
        "official_cleanup_command": "Uninstall OBS Studio, then remove reviewed OBS logs while preserving recordings and profiles.",
        "rationale": "OBS Studio logs are diagnostics; recordings and scene/profile data remain outside this rule.",
    },
    {
        "rule_id": "app-leftovers.spotify.browser-cache",
        "owner": "Spotify",
        "default": "local:Spotify/Browser/Cache",
        "active_markers": ("roaming:Spotify/Spotify.exe", "local:Microsoft/WindowsApps/Spotify.exe"),
        "official_cleanup_command": "Uninstall Spotify from Settings > Apps, then remove reviewed Spotify browser cache leftovers.",
        "rationale": "Spotify browser cache contains regenerated web cache artifacts and does not target downloaded user media.",
    },
    {
        "rule_id": "app-leftovers.spotify.logs",
        "owner": "Spotify",
        "default": "local:Spotify/Logs",
        "active_markers": ("roaming:Spotify/Spotify.exe", "local:Microsoft/WindowsApps/Spotify.exe"),
        "official_cleanup_command": "Uninstall Spotify from Settings > Apps, then remove reviewed Spotify log leftovers.",
        "rationale": "Spotify logs are diagnostic leftovers and do not include playlists or downloaded user media.",
    },
)


def parse_categories(value: str | None) -> list[str]:
    if not value:
        return sorted(DEFAULT_SAFE_CATEGORIES)
    categories = [item.strip() for item in value.split(",") if item.strip()]
    return categories or sorted(DEFAULT_SAFE_CATEGORIES)


def parse_rule_ids(value: str | None) -> list[str]:
    if not value:
        return []
    return [item.strip() for item in value.split(",") if item.strip()]


def _matches_rule_filter(rule_id: str | None, allowed_rule_ids: set[str]) -> bool:
    if not allowed_rule_ids:
        return True
    return bool(rule_id and rule_id in allowed_rule_ids)


def _review_details(*, suggested_paths: list[str], risk_notes: list[str], manual_review_steps: list[str]) -> dict[str, list[str]]:
    return {
        "suggested_paths": suggested_paths,
        "risk_notes": risk_notes,
        "manual_review_steps": manual_review_steps,
    }


def file_size(path: Path) -> int:
    if path.is_file():
        try:
            return path.stat().st_size
        except OSError:
            return 0
    total = 0
    for child in path.rglob("*"):
        try:
            if child.is_file() and not child.is_symlink():
                total += child.stat().st_size
        except OSError:
            continue
    return total


def iso_mtime(path: Path) -> str | None:
    try:
        return datetime.fromtimestamp(path.stat().st_mtime, timezone.utc).isoformat()
    except OSError:
        return None


def older_than_days(path: Path, days: int) -> bool:
    if days <= 0:
        return True
    try:
        age = datetime.now(timezone.utc).timestamp() - path.stat().st_mtime
    except OSError:
        return False
    return age >= days * 86400


def iter_children(root: Path, *, older_than: int, max_items: int) -> Iterable[Path]:
    if not root.exists() or not root.is_dir() or root.is_symlink():
        return []
    found: list[Path] = []
    try:
        children = sorted(root.iterdir(), key=lambda item: item.name.lower())
    except OSError:
        return []
    for child in children:
        if len(found) >= max_items:
            break
        if child.is_symlink() or not older_than_days(child, older_than):
            continue
        found.append(child)
    return found


def candidate_for(
    path: Path,
    *,
    category: str,
    reason: str,
    rule_id: str | None = None,
    cache_owner: str | None = None,
    official_cleanup_command: str | None = None,
    safe_to_delete_rationale: str | None = None,
) -> Candidate | None:
    if not path.exists():
        return None
    try:
        validate_filesystem_candidate(path)
    except RuntimeError:
        return None
    return Candidate(
        path=str(path),
        category=category,
        size_bytes=file_size(path),
        reason=reason,
        safe_to_delete=True,
        risk="low",
        modified_at=iso_mtime(path),
        identity=capture_filesystem_identity(path),
        rule_id=rule_id,
        cache_owner=cache_owner,
        official_cleanup_command=official_cleanup_command,
        safe_to_delete_rationale=safe_to_delete_rationale,
    )


def temp_roots(env: dict[str, str]) -> list[Path]:
    roots: list[Path] = []
    for key in ("TEMP", "TMP"):
        value = env.get(key)
        if value:
            roots.append(Path(value))
    local_app_data = env.get("LOCALAPPDATA")
    if local_app_data:
        roots.append(Path(local_app_data) / "Temp")
    return dedupe_paths(roots)


def _default_rule_path(rule: dict[str, str], *, local_app_data: str | None, user_profile: str | None) -> Path | None:
    default = rule["default"]
    if default.startswith("local:"):
        if not local_app_data:
            return None
        return Path(local_app_data).joinpath(*default.removeprefix("local:").split("/"))
    if default.startswith("home:"):
        if not user_profile:
            return None
        return Path(user_profile).joinpath(*default.removeprefix("home:").split("/"))
    return None


def dev_cache_roots(env: dict[str, str]) -> list[Path]:
    roots: list[Path] = []
    local_app_data = env.get("LOCALAPPDATA")
    user_profile = env.get("USERPROFILE") or env.get("HOME")
    for rule in DEV_CACHE_RULES:
        value = env.get(rule["env_key"])
        if value:
            path = Path(value)
            if rule["rule_id"] == "dev-cache.cargo.registry":
                path = path / "registry" / "cache"
            if rule["rule_id"] == "dev-cache.gradle.caches":
                path = path / "caches"
            roots.append(path)
        default_path = _default_rule_path(rule, local_app_data=local_app_data, user_profile=user_profile)
        if default_path is not None:
            roots.append(default_path)
    return dedupe_paths(roots)


def dev_cache_rule_roots(env: dict[str, str]) -> list[tuple[dict[str, str], Path]]:
    local_app_data = env.get("LOCALAPPDATA")
    user_profile = env.get("USERPROFILE") or env.get("HOME")
    roots: list[tuple[dict[str, str], Path]] = []
    for rule in DEV_CACHE_RULES:
        value = env.get(rule["env_key"])
        paths: list[Path] = []
        if value:
            path = Path(value)
            if rule["rule_id"] == "dev-cache.cargo.registry":
                path = path / "registry" / "cache"
            if rule["rule_id"] == "dev-cache.gradle.caches":
                path = path / "caches"
            paths.append(path)
        default_path = _default_rule_path(rule, local_app_data=local_app_data, user_profile=user_profile)
        if default_path is not None:
            paths.append(default_path)
        for path in dedupe_paths(paths):
            roots.append((rule, path))
    seen: set[str] = set()
    deduped: list[tuple[dict[str, str], Path]] = []
    for rule, path in roots:
        key = str(path.resolve(strict=False)).lower()
        if key in seen:
            continue
        seen.add(key)
        deduped.append((rule, path))
    return deduped


def _default_prefixed_rule_path(
    default: str,
    *,
    local_app_data: str | None,
    user_profile: str | None,
    program_data: str | None,
    roaming_app_data: str | None = None,
    program_files: str | None = None,
    program_files_x86: str | None = None,
) -> Path | None:
    if default.startswith("local:"):
        if not local_app_data:
            return None
        return Path(local_app_data).joinpath(*default.removeprefix("local:").split("/"))
    if default.startswith("home:"):
        if not user_profile:
            return None
        return Path(user_profile).joinpath(*default.removeprefix("home:").split("/"))
    if default.startswith("programdata:"):
        if not program_data:
            return None
        return Path(program_data).joinpath(*default.removeprefix("programdata:").split("/"))
    if default.startswith("roaming:"):
        if not roaming_app_data:
            return None
        return Path(roaming_app_data).joinpath(*default.removeprefix("roaming:").split("/"))
    if default.startswith("programfiles:"):
        if not program_files:
            return None
        return Path(program_files).joinpath(*default.removeprefix("programfiles:").split("/"))
    if default.startswith("programfilesx86:"):
        if not program_files_x86:
            return None
        return Path(program_files_x86).joinpath(*default.removeprefix("programfilesx86:").split("/"))
    return None


def generic_rule_roots(rules: tuple[dict[str, str], ...], env: dict[str, str]) -> list[tuple[dict[str, str], Path]]:
    local_app_data = env.get("LOCALAPPDATA")
    user_profile = env.get("USERPROFILE") or env.get("HOME")
    program_data = env.get("PROGRAMDATA") or r"C:\ProgramData"
    roots: list[tuple[dict[str, str], Path]] = []
    for rule in rules:
        path = _default_prefixed_rule_path(
            rule["default"],
            local_app_data=local_app_data,
            user_profile=user_profile,
            program_data=program_data,
        )
        if path is not None:
            roots.append((rule, path))
    seen: set[str] = set()
    deduped: list[tuple[dict[str, str], Path]] = []
    for rule, path in roots:
        key = str(path.resolve(strict=False)).lower()
        if key in seen:
            continue
        seen.add(key)
        deduped.append((rule, path))
    return deduped


def _expand_existing_wildcard_path(path: Path) -> list[Path]:
    parts = path.parts
    wildcard_index = next((index for index, part in enumerate(parts) if any(char in part for char in "*?[]")), None)
    if wildcard_index is None:
        return [path]
    prefix = Path(parts[0]).joinpath(*parts[1:wildcard_index]) if wildcard_index else Path("*")
    pattern = parts[wildcard_index].lower()
    suffix = parts[wildcard_index + 1 :]
    if not prefix.exists() or not prefix.is_dir() or prefix.is_symlink():
        return []
    expanded: list[Path] = []
    try:
        children = sorted(prefix.iterdir(), key=lambda item: item.name.lower())
    except OSError:
        return []
    for child in children:
        if child.is_symlink() or not fnmatch.fnmatchcase(child.name.lower(), pattern):
            continue
        candidate = child.joinpath(*suffix)
        expanded.extend(_expand_existing_wildcard_path(candidate))
    return expanded


def _active_marker_exists(marker: str, *, env: dict[str, str]) -> bool:
    local_app_data = env.get("LOCALAPPDATA")
    roaming_app_data = env.get("APPDATA")
    user_profile = env.get("USERPROFILE") or env.get("HOME")
    program_data = env.get("PROGRAMDATA") or r"C:\ProgramData"
    program_files = env.get("PROGRAMFILES") or r"C:\Program Files"
    program_files_x86 = env.get("PROGRAMFILES(X86)") or env.get("ProgramFiles(x86)") or r"C:\Program Files (x86)"
    path = _default_prefixed_rule_path(
        marker,
        local_app_data=local_app_data,
        user_profile=user_profile,
        program_data=program_data,
        roaming_app_data=roaming_app_data,
        program_files=program_files,
        program_files_x86=program_files_x86,
    )
    if path is None:
        return False
    return any(candidate.exists() for candidate in _expand_existing_wildcard_path(path))


def app_leftover_rule_roots(env: dict[str, str]) -> list[tuple[dict[str, object], Path]]:
    local_app_data = env.get("LOCALAPPDATA")
    roaming_app_data = env.get("APPDATA")
    user_profile = env.get("USERPROFILE") or env.get("HOME")
    program_data = env.get("PROGRAMDATA") or r"C:\ProgramData"
    program_files = env.get("PROGRAMFILES") or r"C:\Program Files"
    program_files_x86 = env.get("PROGRAMFILES(X86)") or env.get("ProgramFiles(x86)") or r"C:\Program Files (x86)"
    roots: list[tuple[dict[str, object], Path]] = []
    for rule in APP_LEFTOVER_RULES:
        markers = tuple(str(marker) for marker in rule.get("active_markers", ()))
        if any(_active_marker_exists(marker, env=env) for marker in markers):
            continue
        default = str(rule["default"])
        path = _default_prefixed_rule_path(
            default,
            local_app_data=local_app_data,
            user_profile=user_profile,
            program_data=program_data,
            roaming_app_data=roaming_app_data,
            program_files=program_files,
            program_files_x86=program_files_x86,
        )
        if path is None:
            continue
        for expanded in _expand_existing_wildcard_path(path):
            roots.append((rule, expanded))
    seen: set[str] = set()
    deduped: list[tuple[dict[str, object], Path]] = []
    for rule, path in roots:
        key = str(path.resolve(strict=False)).lower()
        if key in seen:
            continue
        seen.add(key)
        deduped.append((rule, path))
    return deduped


def browser_profile_cache_roots(env: dict[str, str]) -> list[tuple[dict[str, str], Path]]:
    local_app_data = env.get("LOCALAPPDATA")
    roaming_app_data = env.get("APPDATA")
    roots: list[tuple[dict[str, str], Path]] = []
    browser_roots: list[tuple[Path, str]] = []
    if local_app_data:
        browser_roots.extend(
            [
                (Path(local_app_data) / "Google" / "Chrome" / "User Data", "chrome"),
                (Path(local_app_data) / "Microsoft" / "Edge" / "User Data", "edge"),
            ]
        )
    for user_data_root, browser_key in browser_roots:
        if not user_data_root.exists() or not user_data_root.is_dir() or user_data_root.is_symlink():
            continue
        try:
            profiles = sorted(user_data_root.iterdir(), key=lambda item: item.name.lower())
        except OSError:
            continue
        for profile in profiles:
            if not profile.is_dir() or profile.is_symlink():
                continue
            for leaf, suffix in (("Cache", "cache"), ("Code Cache", "code-cache")):
                cache_path = profile / leaf
                if cache_path.exists() and cache_path.is_dir() and not cache_path.is_symlink():
                    roots.append((BROWSER_PROFILE_CACHE_RULES[f"{browser_key}-{suffix}"], cache_path))
    firefox_profile_roots: list[Path] = []
    if local_app_data:
        firefox_profile_roots.append(Path(local_app_data) / "Mozilla" / "Firefox" / "Profiles")
    if roaming_app_data:
        firefox_profile_roots.append(Path(roaming_app_data) / "Mozilla" / "Firefox" / "Profiles")
    for profiles_root in firefox_profile_roots:
        if not profiles_root.exists() or not profiles_root.is_dir() or profiles_root.is_symlink():
            continue
        try:
            profiles = sorted(profiles_root.iterdir(), key=lambda item: item.name.lower())
        except OSError:
            continue
        for profile in profiles:
            cache_path = profile / "cache2"
            if cache_path.exists() and cache_path.is_dir() and not cache_path.is_symlink():
                roots.append((BROWSER_PROFILE_CACHE_RULES["firefox-cache2"], cache_path))
    seen: set[str] = set()
    deduped: list[tuple[dict[str, str], Path]] = []
    for rule, path in roots:
        key = str(path.resolve(strict=False)).lower()
        if key in seen:
            continue
        seen.add(key)
        deduped.append((rule, path))
    return deduped


def dedupe_paths(paths: list[Path]) -> list[Path]:
    seen: set[str] = set()
    deduped: list[Path] = []
    for path in paths:
        key = str(path.resolve(strict=False)).lower()
        if key in seen:
            continue
        seen.add(key)
        deduped.append(path)
    return deduped


def collect_candidates(
    categories: list[str],
    *,
    env: dict[str, str] | None = None,
    older_than_days_value: int = 7,
    max_items: int = 100,
    rule_ids: list[str] | None = None,
) -> list[Candidate]:
    env = env or dict(os.environ)
    candidates: list[Candidate] = []
    per_root_limit = max(1, max_items)
    allowed_rule_ids = {item for item in (rule_ids or []) if item}
    if "temp" in categories:
        for root in temp_roots(env):
            for path in iter_children(root, older_than=older_than_days_value, max_items=per_root_limit):
                candidate = candidate_for(path, category="temp", reason=f"Older than {older_than_days_value} days under temp root {root}")
                if candidate:
                    candidates.append(candidate)
                if len(candidates) >= max_items:
                    return candidates
    if "dev-cache" in categories:
        for rule, root in dev_cache_rule_roots(env):
            if not _matches_rule_filter(rule["rule_id"], allowed_rule_ids):
                continue
            for path in iter_children(root, older_than=older_than_days_value, max_items=per_root_limit):
                candidate = candidate_for(
                    path,
                    category="dev-cache",
                    reason=f"{rule['owner']} cache entry under {root}",
                    rule_id=rule["rule_id"],
                    cache_owner=rule["owner"],
                    official_cleanup_command=rule["official_cleanup_command"],
                    safe_to_delete_rationale=rule["rationale"],
                )
                if candidate:
                    candidates.append(candidate)
                if len(candidates) >= max_items:
                    return candidates
    if "package-cache" in categories:
        for rule, root in generic_rule_roots(PACKAGE_CACHE_RULES, env):
            if not _matches_rule_filter(rule["rule_id"], allowed_rule_ids):
                continue
            candidate = candidate_for(
                root,
                category="package-cache",
                reason=f"{rule['owner']} package cache at {root}",
                rule_id=rule["rule_id"],
                cache_owner=rule["owner"],
                official_cleanup_command=rule["official_cleanup_command"],
                safe_to_delete_rationale=rule["rationale"],
            )
            if candidate:
                candidates.append(candidate)
            if len(candidates) >= max_items:
                return candidates
    if "browser-cache" in categories:
        browser_roots = generic_rule_roots(BROWSER_CACHE_RULES, env) + browser_profile_cache_roots(env)
        seen_browser_roots: set[str] = set()
        for rule, root in browser_roots:
            root_key = str(root.resolve(strict=False)).lower()
            if root_key in seen_browser_roots:
                continue
            seen_browser_roots.add(root_key)
            if not _matches_rule_filter(rule["rule_id"], allowed_rule_ids):
                continue
            candidate = candidate_for(
                root,
                category="browser-cache",
                reason=f"{rule['owner']} cache directory at {root}",
                rule_id=rule["rule_id"],
                cache_owner=rule["owner"],
                official_cleanup_command=rule["official_cleanup_command"],
                safe_to_delete_rationale=rule["rationale"],
            )
            if candidate:
                candidates.append(candidate)
            if len(candidates) >= max_items:
                return candidates
    if "app-leftovers" in categories:
        for rule, root in app_leftover_rule_roots(env):
            rule_id = str(rule["rule_id"])
            if not _matches_rule_filter(rule_id, allowed_rule_ids):
                continue
            candidate = candidate_for(
                root,
                category="app-leftovers",
                reason=f"{rule['owner']} uninstall leftover cache/log at {root}",
                rule_id=rule_id,
                cache_owner=str(rule["owner"]),
                official_cleanup_command=str(rule["official_cleanup_command"]),
                safe_to_delete_rationale=str(rule["rationale"]),
            )
            if candidate:
                candidates.append(candidate)
            if len(candidates) >= max_items:
                return candidates
    return candidates


def collect_findings(categories: list[str], *, env: dict[str, str] | None = None, rule_ids: list[str] | None = None) -> list[Finding]:
    env = env or dict(os.environ)
    findings: list[Finding] = []
    allowed_rule_ids = {item for item in (rule_ids or []) if item}
    if "registry-report" in categories:
        finding = Finding(
                category="registry-report",
                title="Registry cleanup is read-only in CleanWin MVP",
                detail="Registry keys are reported for human review only; automatic registry deletion is intentionally unavailable.",
                risk="high",
                rule_id="report.registry.read-only",
                owner="Windows Registry",
                official_cleanup_command="Use vendor uninstallers, Settings > Apps, or regedit after manual backup and review.",
                review_details=_review_details(
                    suggested_paths=[r"HKCU\\Software", r"HKLM\\Software"],
                    risk_notes=["Registry deletes are irreversible without backup.", "Shared keys may affect multiple apps or Windows features."],
                    manual_review_steps=["Export affected keys before any change.", "Prefer vendor uninstallers before regedit cleanup."],
                ),
            )
        if _matches_rule_filter(finding.rule_id, allowed_rule_ids):
            findings.append(finding)
    if "startup-report" in categories:
        finding = Finding(
                category="startup-report",
                title="Startup changes are read-only in CleanWin MVP",
                detail="Run keys, startup folders, services, scheduled tasks, and policy-managed entries are not disabled automatically.",
                risk="medium",
                rule_id="report.startup.read-only",
                owner="Windows startup configuration",
                official_cleanup_command="Use Task Manager Startup Apps, Services, Task Scheduler, or vendor settings after manual review.",
                review_details=_review_details(
                    suggested_paths=[r"%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\Startup", r"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run"],
                    risk_notes=["Startup entries may be policy-managed or required for security tooling.", "Disabling services can change login, sync, or update behavior."],
                    manual_review_steps=["Review publisher and command target before disabling.", "Prefer Task Manager or vendor settings to disable startup items."],
                ),
            )
        if _matches_rule_filter(finding.rule_id, allowed_rule_ids):
            findings.append(finding)
    if "windows-report" in categories:
        finding = Finding(
                category="windows-report",
                title="Windows component stores require official tools",
                detail="WinSxS, Installer, SoftwareDistribution, Defender, and Delivery Optimization paths are protected from direct deletion.",
                risk="high",
                rule_id="report.windows.official-tools",
                owner="Windows servicing",
                official_cleanup_command="Use Disk Cleanup, Storage Sense, DISM /Online /Cleanup-Image /StartComponentCleanup, or Windows Update UI.",
                review_details=_review_details(
                    suggested_paths=[r"C:\\Windows\\WinSxS", r"C:\\Windows\\SoftwareDistribution", r"C:\\ProgramData\\Microsoft\\Windows\\DeliveryOptimization"],
                    risk_notes=["Direct deletion can break servicing stack integrity.", "Windows may require these stores for rollback and repair."],
                    manual_review_steps=["Use DISM or Storage Sense instead of Explorer deletion.", "Verify pending Windows Update state before cleanup."],
                ),
            )
        if _matches_rule_filter(finding.rule_id, allowed_rule_ids):
            findings.append(finding)
    if "large-files" in categories:
        finding = Finding(
                category="large-files",
                title="Large files are report-only",
                detail="Downloads, Documents, Desktop, OneDrive, and SharePoint roots are protected from automatic deletion.",
                risk="medium",
                rule_id="report.large-files.read-only",
                owner="User files",
                official_cleanup_command="Review in File Explorer or Storage Settings; do not bulk-delete automatically.",
                review_details=_review_details(
                    suggested_paths=[r"%USERPROFILE%\\Downloads", r"%USERPROFILE%\\Desktop", r"%USERPROFILE%\\OneDrive"],
                    risk_notes=["Large files often include user documents and synced content.", "Cloud-backed paths may rehydrate or trigger sync churn."],
                    manual_review_steps=["Sort by size in File Explorer.", "Confirm backup or sync state before removing files."],
                ),
            )
        if _matches_rule_filter(finding.rule_id, allowed_rule_ids):
            findings.append(finding)
    if "docker-report" in categories:
        docker_local = env.get("LOCALAPPDATA")
        docker_paths = [r"%LOCALAPPDATA%\\Docker", r"%LOCALAPPDATA%\\Docker\\wsl", r"%LOCALAPPDATA%\\Docker\\log"]
        if docker_local:
            docker_paths = [str(Path(docker_local) / "Docker"), str(Path(docker_local) / "Docker" / "wsl"), str(Path(docker_local) / "Docker" / "log")]
        finding = Finding(
                category="docker-report",
                title="Docker cleanup is read-only",
                detail="Docker images, containers, volumes, BuildKit cache, and Docker Desktop WSL data are reported only because volumes may contain durable application data.",
                risk="high",
                rule_id="report.docker.manual-cleanup",
                owner="Docker Desktop",
                official_cleanup_command="docker system df; docker builder prune; docker system prune --volumes only after manual review",
                review_details=_review_details(
                    suggested_paths=docker_paths,
                    risk_notes=["Docker volumes may contain databases or local development state.", "Docker Desktop may store WSL disk images that should not be deleted directly."],
                    manual_review_steps=["Inspect disk usage with docker system df.", "Prune builder cache before considering image/container cleanup.", "Review named volumes before any docker system prune --volumes."],
                ),
            )
        if _matches_rule_filter(finding.rule_id, allowed_rule_ids):
            findings.append(finding)
    if "wsl-report" in categories:
        wsl_local = env.get("LOCALAPPDATA")
        wsl_paths = [r"%LOCALAPPDATA%\\Packages", r"%USERPROFILE%\\AppData\\Local\\lxss"]
        if wsl_local:
            wsl_paths = [str(Path(wsl_local) / "Packages"), str(Path(wsl_local) / "lxss")]
        finding = Finding(
                category="wsl-report",
                title="WSL cleanup is read-only",
                detail="WSL distributions, ext4.vhdx files, package caches, and distro home directories are never cleaned by direct file deletion.",
                risk="high",
                rule_id="report.wsl.manual-cleanup",
                owner="WSL",
                official_cleanup_command="wsl --list --verbose; use distro package managers or wsl --unregister only after backup and review",
                review_details=_review_details(
                    suggested_paths=wsl_paths,
                    risk_notes=["ext4.vhdx files contain entire Linux filesystems.", "Manual file deletion can corrupt registered distros."],
                    manual_review_steps=["List distros with wsl --list --verbose.", "Clean package caches inside each distro first.", "Export or back up a distro before unregistering it."],
                ),
            )
        if _matches_rule_filter(finding.rule_id, allowed_rule_ids):
            findings.append(finding)
    if "visual-studio-report" in categories:
        user_profile = env.get("USERPROFILE") or env.get("HOME")
        vs_paths = [r"%LOCALAPPDATA%\\Microsoft\\VisualStudio", r"%USERPROFILE%\\.nuget\\packages"]
        if user_profile:
            vs_paths[1] = str(Path(user_profile) / ".nuget" / "packages")
        finding = Finding(
                category="visual-studio-report",
                title="Visual Studio cleanup is read-only",
                detail="Visual Studio component caches, workloads, NuGet integration, and installer state are reported only; direct deletion can break repair and updates.",
                risk="medium",
                rule_id="report.visual-studio.official-tools",
                owner="Visual Studio",
                official_cleanup_command="Use Visual Studio Installer modify/repair and dotnet nuget locals all --clear for NuGet caches.",
                review_details=_review_details(
                    suggested_paths=vs_paths,
                    risk_notes=["Installer state is shared across workloads and SDKs.", "Deleting caches blindly can trigger repair loops or broken updates."],
                    manual_review_steps=["Use Visual Studio Installer to remove unused workloads.", "Clear NuGet caches with official dotnet or nuget commands first."],
                ),
            )
        if _matches_rule_filter(finding.rule_id, allowed_rule_ids):
            findings.append(finding)
    if "browser-cache-report" in categories:
        local_app_data = env.get("LOCALAPPDATA")
        roaming_app_data = env.get("APPDATA")
        browser_paths = [r"%LOCALAPPDATA%\\Google\\Chrome\\User Data", r"%LOCALAPPDATA%\\Microsoft\\Edge\\User Data", r"%APPDATA%\\Mozilla\\Firefox\\Profiles"]
        if local_app_data:
            browser_paths[0] = str(Path(local_app_data) / "Google" / "Chrome" / "User Data")
            browser_paths[1] = str(Path(local_app_data) / "Microsoft" / "Edge" / "User Data")
        if roaming_app_data:
            browser_paths[2] = str(Path(roaming_app_data) / "Mozilla" / "Firefox" / "Profiles")
        finding = Finding(
                category="browser-cache-report",
                title="Browser cache cleanup is read-only",
                detail="Browser profiles include cache next to cookies, sessions, extension state, passwords, and synced data; CleanWin does not delete browser profile files directly.",
                risk="high",
                rule_id="report.browser-cache.in-app-cleanup",
                owner="Browsers",
                official_cleanup_command="Use each browser's Clear browsing data UI and keep passwords, cookies, sessions, and synced profile data under user control.",
                review_details=_review_details(
                    suggested_paths=browser_paths,
                    risk_notes=["Browser profiles mix cache with authentication sessions and extensions.", "Manual deletion can sign users out or corrupt profiles."],
                    manual_review_steps=["Use browser-native Clear browsing data controls.", "Prefer clearing cached images/files without removing passwords or cookies unless requested."],
                ),
            )
        if _matches_rule_filter(finding.rule_id, allowed_rule_ids):
            findings.append(finding)
    unknown = sorted(set(categories) - DEFAULT_SAFE_CATEGORIES - READ_ONLY_CATEGORIES)
    for category in unknown:
        findings.append(
            Finding(
                category=category,
                title=f"Unknown category: {category}",
                detail="No collector is registered; no actions were planned.",
                risk="low",
            )
        )
    return findings
