"""Read-only debloat and privacy telemetry reporting."""

from __future__ import annotations

import os
import platform
from collections.abc import Iterable, Mapping
from pathlib import Path
from typing import Any

from cleanwincli.report_helpers import get_env, source_status

DEBLOAT_PRIVACY_REPORT_SCHEMA = "cleanwin.debloat-privacy-report.v1"

_POLICY_SPECS: tuple[tuple[str, str, str, str, str, set[int | str], str, list[str]], ...] = (
    (
        "privacy.telemetry.allow-telemetry",
        "Windows telemetry policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\DataCollection",
        "AllowTelemetry",
        {0},
        "high",
        ["Review organization policy before changing telemetry settings.", "Export the policy key before any future registry mutation."],
    ),
    (
        "privacy.ad-id.disabled",
        "Advertising ID policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\AdvertisingInfo",
        "Enabled",
        {0},
        "medium",
        ["Use Windows Privacy settings where possible.", "Confirm app compatibility before changing advertising ID state."],
    ),
    (
        "privacy.consumer-features.disabled",
        "Consumer features policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\CloudContent",
        "DisableWindowsConsumerFeatures",
        {1},
        "medium",
        ["Review managed policy ownership.", "Export the policy key before any future registry mutation."],
    ),
    (
        "privacy.copilot.disabled",
        "Windows Copilot policy",
        "HKCU",
        r"Software\Policies\Microsoft\Windows\WindowsCopilot",
        "TurnOffWindowsCopilot",
        {1},
        "medium",
        ["Confirm Windows version support.", "Prefer Settings or policy management over direct registry edits."],
    ),
    (
        "privacy.recall.disabled",
        "Windows Recall AI data analysis policy",
        "HKCU",
        r"Software\Policies\Microsoft\Windows\WindowsAI",
        "DisableAIDataAnalysis",
        {1},
        "high",
        ["Confirm Windows edition and policy support.", "Export the WindowsAI policy key before any future mutation."],
    ),
    (
        "privacy.tailored-experiences.disabled",
        "Tailored experiences with diagnostic data",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\Privacy",
        "TailoredExperiencesWithDiagnosticDataEnabled",
        {0},
        "medium",
        ["Prefer Windows Privacy settings where possible.", "Record current value before any policy change."],
    ),
    (
        "privacy.activity-history.publish-disabled",
        "Activity history publishing policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\System",
        "PublishUserActivities",
        {0},
        "medium",
        ["Review Timeline/activity history expectations.", "Export the Windows System policy key before mutation."],
    ),
    (
        "privacy.activity-history.upload-disabled",
        "Activity history upload policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\System",
        "UploadUserActivities",
        {0},
        "medium",
        ["Review cross-device activity history expectations.", "Export the Windows System policy key before mutation."],
    ),
    (
        "privacy.feedback-notifications.disabled",
        "Feedback notification policy",
        "HKCU",
        r"Software\Policies\Microsoft\Windows\DataCollection",
        "DoNotShowFeedbackNotifications",
        {1},
        "low",
        ["Confirm user notification preference.", "Use policy management instead of ad hoc registry edits."],
    ),
    (
        "privacy.diagnostic-data-viewer.disabled",
        "Diagnostic Data Viewer policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\DataCollection",
        "DisableDiagnosticDataViewer",
        {1},
        "medium",
        ["Review diagnostics workflow expectations.", "Export the DataCollection policy key before any future registry mutation."],
    ),
    (
        "privacy.search-cortana.disabled",
        "Cortana search policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\Windows Search",
        "AllowCortana",
        {0},
        "medium",
        ["Confirm Windows Search behavior expectations.", "Export Windows Search policy before mutation."],
    ),
    (
        "privacy.spotlight.disabled",
        "Windows Spotlight policy",
        "HKCU",
        r"Software\Policies\Microsoft\Windows\CloudContent",
        "DisableWindowsSpotlightFeatures",
        {1},
        "low",
        ["Review lock screen and Spotlight preference.", "Prefer policy or Settings UI for future changes."],
    ),
    (
        "privacy.lock-screen-spotlight.disabled",
        "Lock screen Spotlight policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager",
        "RotatingLockScreenEnabled",
        {0},
        "low",
        ["Review lock screen content preference.", "Prefer Settings UI before registry mutation."],
    ),
    (
        "privacy.location.disabled",
        "Location services policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\LocationAndSensors",
        "DisableLocation",
        {1},
        "medium",
        ["Review location-dependent apps and device management policy.", "Export LocationAndSensors policy before mutation."],
    ),
    (
        "privacy.find-my-device.disabled",
        "Find My Device policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\FindMyDevice",
        "AllowFindMyDevice",
        {0},
        "medium",
        ["Review device recovery expectations before disabling location-based recovery.", "Export FindMyDevice policy before mutation."],
    ),
    (
        "privacy.app-diagnostics.disabled",
        "Application diagnostics access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\appDiagnostics",
        "Value",
        {"Deny"},
        "medium",
        ["Review apps that require diagnostic access.", "Prefer Windows Privacy settings before any registry mutation."],
    ),
    (
        "privacy.online-speech.disabled",
        "Online speech recognition policy",
        "HKCU",
        r"Software\Microsoft\Speech_OneCore\Settings\OnlineSpeechPrivacy",
        "HasAccepted",
        {0},
        "medium",
        ["Review dictation and speech recognition workflows.", "Prefer Windows Privacy settings before registry mutation."],
    ),
    (
        "privacy.implicit-ink-collection.disabled",
        "Implicit ink collection policy",
        "HKCU",
        r"Software\Policies\Microsoft\InputPersonalization",
        "RestrictImplicitInkCollection",
        {1},
        "medium",
        ["Review pen and handwriting personalization workflows.", "Export InputPersonalization policy before mutation."],
    ),
    (
        "privacy.implicit-text-collection.disabled",
        "Implicit text collection policy",
        "HKCU",
        r"Software\Policies\Microsoft\InputPersonalization",
        "RestrictImplicitTextCollection",
        {1},
        "medium",
        ["Review typing personalization workflows.", "Export InputPersonalization policy before mutation."],
    ),
    (
        "privacy.webcam-access.disabled",
        "Camera access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam",
        "Value",
        {"Deny"},
        "medium",
        ["Review conferencing and capture workflows before changing camera access.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.microphone-access.disabled",
        "Microphone access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\microphone",
        "Value",
        {"Deny"},
        "medium",
        ["Review conferencing and audio workflows before changing microphone access.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.account-info-access.disabled",
        "Account information access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\userAccountInformation",
        "Value",
        {"Deny"},
        "medium",
        ["Review Microsoft account and app sign-in behavior.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.contacts-access.disabled",
        "Contacts access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\contacts",
        "Value",
        {"Deny"},
        "medium",
        ["Review mail/contact app workflows before changing access.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.calendar-access.disabled",
        "Calendar access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\appointments",
        "Value",
        {"Deny"},
        "medium",
        ["Review calendar app workflows before changing access.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.notifications-access.disabled",
        "Notification access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\userNotificationListener",
        "Value",
        {"Deny"},
        "low",
        ["Review apps that depend on notification listener access.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.smartscreen.enabled",
        "Windows SmartScreen policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\System",
        "EnableSmartScreen",
        {1},
        "high",
        ["Treat SmartScreen as security-sensitive; do not disable it as privacy cleanup.", "Export Windows System policy before mutation."],
    ),
    (
        "privacy.edge-smartscreen.enabled",
        "Microsoft Edge SmartScreen policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "SmartScreenEnabled",
        {1},
        "high",
        ["Treat browser SmartScreen as security-sensitive; do not disable it as privacy cleanup.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.search-cloud-content.disabled",
        "Windows Search cloud content policy",
        "HKCU",
        r"Software\Policies\Microsoft\Windows\Windows Search",
        "AllowCloudSearch",
        {0},
        "medium",
        ["Review work/school account search expectations.", "Export Windows Search policy before mutation."],
    ),
    (
        "privacy.start-suggestions.disabled",
        "Start menu suggestions policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager",
        "SubscribedContent-338388Enabled",
        {0},
        "low",
        ["Review Start menu content suggestions preference.", "Prefer Settings UI before registry mutation."],
    ),
    (
        "privacy.settings-suggestions.disabled",
        "Settings app suggestions policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager",
        "SubscribedContent-338393Enabled",
        {0},
        "low",
        ["Review Settings suggestion preference.", "Prefer Settings UI before registry mutation."],
    ),
    (
        "privacy.third-party-suggestions.disabled",
        "Third-party content suggestions policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager",
        "SubscribedContent-338389Enabled",
        {0},
        "low",
        ["Review cloud content suggestions preference.", "Export ContentDeliveryManager values before mutation."],
    ),
    (
        "privacy.silent-installed-apps.disabled",
        "Silent installed apps suggestion policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager",
        "SilentInstalledAppsEnabled",
        {0},
        "medium",
        ["Review OEM or consumer app provisioning behavior.", "Export ContentDeliveryManager values before mutation."],
    ),
    (
        "privacy.widgets.disabled",
        "Widgets policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Dsh",
        "AllowNewsAndInterests",
        {0},
        "low",
        ["Review Widgets and News interests user preference.", "Use policy management before registry mutation."],
    ),
    (
        "privacy.edge-personalization-reporting.disabled",
        "Microsoft Edge personalization reporting policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "PersonalizationReportingEnabled",
        {0},
        "medium",
        ["Review Edge managed policy ownership.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.edge-shopping-assistant.disabled",
        "Microsoft Edge shopping assistant policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "EdgeShoppingAssistantEnabled",
        {0},
        "low",
        ["Review Edge shopping and recommendations preference.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.telemetry-opt-in-settings.disabled",
        "Telemetry opt-in settings UX policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\DataCollection",
        "DisableTelemetryOptInSettingsUx",
        {1},
        "medium",
        ["Review diagnostics UX expectations.", "Export the DataCollection policy key before mutation."],
    ),
    (
        "privacy.device-name-in-telemetry.disabled",
        "Device name in diagnostic data policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\DataCollection",
        "AllowDeviceNameInTelemetry",
        {0},
        "medium",
        ["Review enterprise diagnostics requirements.", "Export the DataCollection policy key before mutation."],
    ),
    (
        "privacy.diagnostic-log-collection.limited",
        "Diagnostic log collection limit policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\DataCollection",
        "LimitDiagnosticLogCollection",
        {1},
        "medium",
        ["Review support diagnostics requirements.", "Export the DataCollection policy key before mutation."],
    ),
    (
        "privacy.dump-collection.limited",
        "Diagnostic dump collection limit policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\DataCollection",
        "LimitDumpCollection",
        {1},
        "medium",
        ["Review crash diagnostics requirements.", "Export the DataCollection policy key before mutation."],
    ),
    (
        "privacy.wer.disabled",
        "Windows Error Reporting policy",
        "HKLM",
        r"SOFTWARE\Microsoft\Windows\Windows Error Reporting",
        "Disabled",
        {1},
        "medium",
        ["Review crash reporting and support workflows.", "Export the Windows Error Reporting key before mutation."],
    ),
    (
        "privacy.ceip.disabled",
        "Customer Experience Improvement Program policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\SQMClient\Windows",
        "CEIPEnable",
        {0},
        "medium",
        ["Review diagnostics participation policy.", "Export the SQMClient policy key before mutation."],
    ),
    (
        "privacy.feedback-frequency.disabled",
        "Feedback frequency policy",
        "HKCU",
        r"Software\Microsoft\Siuf\Rules",
        "NumberOfSIUFInPeriod",
        {0},
        "low",
        ["Review Windows feedback prompts preference.", "Export the SIUF key before mutation."],
    ),
    (
        "privacy.feedback-period.disabled",
        "Feedback period policy",
        "HKCU",
        r"Software\Microsoft\Siuf\Rules",
        "PeriodInNanoSeconds",
        {0},
        "low",
        ["Review Windows feedback prompt cadence.", "Export the SIUF key before mutation."],
    ),
    (
        "privacy.experimentation.disabled",
        "Windows experimentation policy",
        "HKLM",
        r"SOFTWARE\Microsoft\PolicyManager\default\System\AllowExperimentation",
        "value",
        {0},
        "medium",
        ["Review Windows feature experimentation policy.", "Export the PolicyManager key before mutation."],
    ),
    (
        "privacy.preview-builds.disabled",
        "Preview builds policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\PreviewBuilds",
        "AllowBuildPreview",
        {0},
        "medium",
        ["Review Insider/preview build enrollment.", "Export the PreviewBuilds policy key before mutation."],
    ),
    (
        "privacy.search-web-results.disabled",
        "Windows Search web results policy",
        "HKCU",
        r"Software\Policies\Microsoft\Windows\Explorer",
        "DisableSearchBoxSuggestions",
        {1},
        "medium",
        ["Review Start/Search web results behavior.", "Export the Explorer policy key before mutation."],
    ),
    (
        "privacy.search-location.disabled",
        "Search location usage policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\Search",
        "AllowSearchToUseLocation",
        {0},
        "medium",
        ["Review local search and location behavior.", "Export the Search key before mutation."],
    ),
    (
        "privacy.search-history.disabled",
        "Search history device policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\SearchSettings",
        "IsDeviceSearchHistoryEnabled",
        {0},
        "low",
        ["Review search history preference.", "Prefer Settings UI before registry mutation."],
    ),
    (
        "privacy.bing-search.disabled",
        "Bing Search integration policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\Search",
        "BingSearchEnabled",
        {0},
        "medium",
        ["Review Windows Search web integration.", "Export the Search key before mutation."],
    ),
    (
        "privacy.cortana-consent.disabled",
        "Cortana consent policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\Search",
        "CortanaConsent",
        {0},
        "medium",
        ["Review assistant/search behavior.", "Export the Search key before mutation."],
    ),
    (
        "privacy.cloud-clipboard.disabled",
        "Cloud clipboard policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\System",
        "AllowClipboardHistory",
        {0},
        "medium",
        ["Review clipboard history and sync needs.", "Export the Windows System policy key before mutation."],
    ),
    (
        "privacy.clipboard-sync.disabled",
        "Clipboard cross-device sync policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\System",
        "AllowCrossDeviceClipboard",
        {0},
        "medium",
        ["Review cross-device clipboard workflows.", "Export the Windows System policy key before mutation."],
    ),
    (
        "privacy.nearby-sharing.disabled",
        "Nearby sharing policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\System",
        "EnableCdp",
        {0},
        "medium",
        ["Review cross-device experiences.", "Export the Windows System policy key before mutation."],
    ),
    (
        "privacy.shared-experiences.disabled",
        "Shared experiences policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\System",
        "UploadUserActivities",
        {0},
        "medium",
        ["Review cross-device activity expectations.", "Export the Windows System policy key before mutation."],
    ),
    (
        "privacy.content-delivery-preinstalled-apps.disabled",
        "Preinstalled app content delivery policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager",
        "PreInstalledAppsEnabled",
        {0},
        "medium",
        ["Review consumer app provisioning behavior.", "Export ContentDeliveryManager values before mutation."],
    ),
    (
        "privacy.content-delivery-oem-preinstalled-apps.disabled",
        "OEM preinstalled app content delivery policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager",
        "OemPreInstalledAppsEnabled",
        {0},
        "medium",
        ["Review OEM app provisioning behavior.", "Export ContentDeliveryManager values before mutation."],
    ),
    (
        "privacy.content-delivery-preinstalled-apps-ever.disabled",
        "Preinstalled apps ever enabled policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager",
        "PreInstalledAppsEverEnabled",
        {0},
        "low",
        ["Review content delivery state.", "Export ContentDeliveryManager values before mutation."],
    ),
    (
        "privacy.content-delivery-system-pane-suggestions.disabled",
        "System pane suggestions policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager",
        "SystemPaneSuggestionsEnabled",
        {0},
        "low",
        ["Review system suggestion preference.", "Export ContentDeliveryManager values before mutation."],
    ),
    (
        "privacy.content-delivery-soft-landing.disabled",
        "Soft landing content policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager",
        "SoftLandingEnabled",
        {0},
        "low",
        ["Review Windows tips preference.", "Export ContentDeliveryManager values before mutation."],
    ),
    (
        "privacy.content-delivery-feature-management.disabled",
        "Feature management content delivery policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager",
        "FeatureManagementEnabled",
        {0},
        "low",
        ["Review feature recommendation preference.", "Export ContentDeliveryManager values before mutation."],
    ),
    (
        "privacy.content-delivery-rotating-lock-screen-overlay.disabled",
        "Rotating lock screen overlay policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager",
        "RotatingLockScreenOverlayEnabled",
        {0},
        "low",
        ["Review lock-screen content preference.", "Export ContentDeliveryManager values before mutation."],
    ),
    (
        "privacy.content-delivery-suggested-apps.disabled",
        "Suggested apps content policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager",
        "SubscribedContent-338387Enabled",
        {0},
        "low",
        ["Review suggested app content preference.", "Export ContentDeliveryManager values before mutation."],
    ),
    (
        "privacy.content-delivery-tips.disabled",
        "Windows tips content policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager",
        "SubscribedContent-338389Enabled",
        {0},
        "low",
        ["Review tips and suggestion preference.", "Export ContentDeliveryManager values before mutation."],
    ),
    (
        "privacy.content-delivery-welcome.disabled",
        "Windows welcome experience policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager",
        "SubscribedContent-310093Enabled",
        {0},
        "low",
        ["Review post-update welcome experience preference.", "Export ContentDeliveryManager values before mutation."],
    ),
    (
        "privacy.edge-search-suggestions.disabled",
        "Microsoft Edge search suggestions policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "SearchSuggestEnabled",
        {0},
        "medium",
        ["Review Edge search suggestion behavior.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.edge-alternate-error-pages.disabled",
        "Microsoft Edge alternate error pages policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "AlternateErrorPagesEnabled",
        {0},
        "low",
        ["Review Edge navigation assistance preference.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.edge-network-prediction.disabled",
        "Microsoft Edge network prediction policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "NetworkPredictionOptions",
        {2},
        "medium",
        ["Review browsing performance and privacy tradeoffs.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.edge-payment-autofill.disabled",
        "Microsoft Edge payment autofill policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "AutofillCreditCardEnabled",
        {0},
        "medium",
        ["Review browser autofill expectations.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.edge-address-autofill.disabled",
        "Microsoft Edge address autofill policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "AutofillAddressEnabled",
        {0},
        "medium",
        ["Review browser autofill expectations.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.edge-metrics-reporting.disabled",
        "Microsoft Edge metrics reporting policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "MetricsReportingEnabled",
        {0},
        "medium",
        ["Review Edge diagnostics policy.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.edge-typosquatting-checker.enabled",
        "Microsoft Edge typosquatting checker policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "TyposquattingCheckerEnabled",
        {1},
        "high",
        ["Treat phishing protection as security-sensitive.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.app-permission-email.disabled",
        "Email access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\email",
        "Value",
        {"Deny"},
        "medium",
        ["Review mail app workflows before changing access.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.app-permission-tasks.disabled",
        "Tasks access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\userDataTasks",
        "Value",
        {"Deny"},
        "medium",
        ["Review task app workflows before changing access.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.app-permission-call-history.disabled",
        "Call history access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\phoneCallHistory",
        "Value",
        {"Deny"},
        "medium",
        ["Review phone integration workflows before changing access.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.app-permission-phone-calls.disabled",
        "Phone call access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\phoneCall",
        "Value",
        {"Deny"},
        "medium",
        ["Review phone integration workflows before changing access.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.app-permission-radios.disabled",
        "Radios access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\radios",
        "Value",
        {"Deny"},
        "medium",
        ["Review Bluetooth/radio workflows before changing access.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.app-permission-bluetooth-sync.disabled",
        "Bluetooth sync access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\bluetoothSync",
        "Value",
        {"Deny"},
        "medium",
        ["Review Bluetooth sync workflows before changing access.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.app-permission-documents.disabled",
        "Documents library access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\documentsLibrary",
        "Value",
        {"Deny"},
        "medium",
        ["Review document library app workflows before changing access.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.app-permission-downloads.disabled",
        "Downloads folder access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\downloadsFolder",
        "Value",
        {"Deny"},
        "medium",
        ["Review downloads folder app workflows before changing access.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.app-permission-pictures.disabled",
        "Pictures library access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\picturesLibrary",
        "Value",
        {"Deny"},
        "medium",
        ["Review pictures library app workflows before changing access.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.app-permission-videos.disabled",
        "Videos library access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\videosLibrary",
        "Value",
        {"Deny"},
        "medium",
        ["Review videos library app workflows before changing access.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.app-permission-music.disabled",
        "Music library access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\musicLibrary",
        "Value",
        {"Deny"},
        "medium",
        ["Review music library app workflows before changing access.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.app-permission-broad-file-system.disabled",
        "Broad file system access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\broadFileSystemAccess",
        "Value",
        {"Deny"},
        "high",
        ["Review broad filesystem app access carefully.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.app-permission-chat.disabled",
        "Chat access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\chat",
        "Value",
        {"Deny"},
        "medium",
        ["Review communication app workflows before changing access.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.app-permission-gaze-input.disabled",
        "Eye tracking access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\gazeInput",
        "Value",
        {"Deny"},
        "medium",
        ["Review accessibility workflows before changing eye tracking access.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.app-permission-cellular-data.disabled",
        "Cellular data access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\cellularData",
        "Value",
        {"Deny"},
        "medium",
        ["Review cellular modem workflows before changing access.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.app-permission-user-data-disabled",
        "User data access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\userData",
        "Value",
        {"Deny"},
        "medium",
        ["Review app data access expectations.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.app-permission-background-apps.disabled",
        "Background apps access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications",
        "GlobalUserDisabled",
        {1},
        "medium",
        ["Review apps that depend on background execution.", "Export BackgroundAccessApplications before mutation."],
    ),
    (
        "privacy.input-personalization.disabled",
        "Input personalization policy",
        "HKCU",
        r"Software\Microsoft\InputPersonalization",
        "RestrictImplicitTextCollection",
        {1},
        "medium",
        ["Review typing personalization workflows.", "Prefer Settings or policy management before registry mutation."],
    ),
    (
        "privacy.input-personalization-contacts.disabled",
        "Input personalization contact harvesting policy",
        "HKCU",
        r"Software\Microsoft\InputPersonalization\TrainedDataStore",
        "HarvestContacts",
        {0},
        "medium",
        ["Review contact-based personalization behavior.", "Export TrainedDataStore before mutation."],
    ),
    (
        "privacy.handwriting-error-reports.disabled",
        "Handwriting error reporting policy",
        "HKCU",
        r"Software\Policies\Microsoft\Windows\HandwritingErrorReports",
        "PreventHandwritingErrorReports",
        {1},
        "medium",
        ["Review handwriting diagnostics requirements.", "Export HandwritingErrorReports policy before mutation."],
    ),
    (
        "privacy.text-prediction.disabled",
        "Text prediction policy",
        "HKCU",
        r"Software\Microsoft\TabletTip\1.7",
        "EnableTextPrediction",
        {0},
        "low",
        ["Review typing assistance preference.", "Prefer Settings UI before registry mutation."],
    ),
    (
        "privacy.sync-settings.disabled",
        "Windows settings sync policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\SettingSync",
        "DisableSettingSync",
        {2},
        "medium",
        ["Review Microsoft account sync workflows.", "Export SettingSync policy before mutation."],
    ),
    (
        "privacy.sync-settings-user-override.disabled",
        "Windows settings sync user override policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\SettingSync",
        "DisableSettingSyncUserOverride",
        {1},
        "medium",
        ["Review managed-device policy ownership.", "Export SettingSync policy before mutation."],
    ),
    (
        "privacy.sync-credentials.disabled",
        "Credentials sync policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\SettingSync",
        "DisableCredentialsSettingSync",
        {2},
        "high",
        ["Review credential sync and account recovery workflows.", "Export SettingSync policy before mutation."],
    ),
    (
        "privacy.sync-browser-settings.disabled",
        "Browser settings sync policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\SettingSync",
        "DisableBrowserSettingsSettingSync",
        {2},
        "medium",
        ["Review browser setting sync workflows.", "Export SettingSync policy before mutation."],
    ),
    (
        "privacy.sync-desktop-theme.disabled",
        "Desktop theme sync policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\SettingSync",
        "DisableDesktopThemeSettingSync",
        {2},
        "low",
        ["Review personalization sync preference.", "Export SettingSync policy before mutation."],
    ),
    (
        "privacy.sync-language.disabled",
        "Language settings sync policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\SettingSync",
        "DisableLanguageSettingSync",
        {2},
        "low",
        ["Review language preference sync.", "Export SettingSync policy before mutation."],
    ),
    (
        "privacy.cloud-content-account-notifications.disabled",
        "Microsoft account cloud notification policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager",
        "SubscribedContent-353694Enabled",
        {0},
        "low",
        ["Review account notification preference.", "Export ContentDeliveryManager values before mutation."],
    ),
    (
        "privacy.cloud-content-privacy-settings-suggestions.disabled",
        "Privacy settings suggestions policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager",
        "SubscribedContent-353696Enabled",
        {0},
        "low",
        ["Review privacy recommendation preference.", "Export ContentDeliveryManager values before mutation."],
    ),
    (
        "privacy.cloud-content-windows-tips.disabled",
        "Windows tips subscription policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager",
        "SubscribedContent-338393Enabled",
        {0},
        "low",
        ["Review Windows tips preference.", "Export ContentDeliveryManager values before mutation."],
    ),
    (
        "privacy.cloud-content-app-suggestions.disabled",
        "App suggestions subscription policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager",
        "SubscribedContent-338388Enabled",
        {0},
        "low",
        ["Review app suggestion preference.", "Export ContentDeliveryManager values before mutation."],
    ),
    (
        "privacy.delivery-optimization-internet-peering.disabled",
        "Delivery Optimization internet peer policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\DeliveryOptimization",
        "DODownloadMode",
        {0, 1, 99, 100},
        "medium",
        ["Review Delivery Optimization bandwidth policy.", "Prefer Settings or policy management before registry mutation."],
    ),
    (
        "privacy.delivery-optimization-group-id-source.disabled",
        "Delivery Optimization group ID source policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\DeliveryOptimization",
        "DOGroupIdSource",
        {0},
        "medium",
        ["Review managed update distribution expectations.", "Export DeliveryOptimization policy before mutation."],
    ),
    (
        "privacy.windows-update-feature-recommendations.disabled",
        "Windows Update feature recommendations policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate",
        "DisableDualScan",
        {1},
        "medium",
        ["Review enterprise update management expectations.", "Export WindowsUpdate policy before mutation."],
    ),
    (
        "privacy.windows-update-driver-search.disabled",
        "Windows Update driver search policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\DriverSearching",
        "DontSearchWindowsUpdate",
        {1},
        "medium",
        ["Review driver update workflow before changing update search.", "Export DriverSearching policy before mutation."],
    ),
    (
        "privacy.defender-sample-submission.prompt",
        "Defender sample submission policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows Defender\Spynet",
        "SubmitSamplesConsent",
        {0, 1},
        "high",
        ["Treat Defender sample submission as security-sensitive.", "Do not weaken Defender protections as privacy cleanup."],
    ),
    (
        "privacy.defender-spynet-reporting.enabled",
        "Defender cloud protection policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows Defender\Spynet",
        "SpynetReporting",
        {1, 2},
        "high",
        ["Treat Defender cloud protection as security-sensitive.", "Review security ownership before any policy change."],
    ),
    (
        "privacy.defender-pua-protection.enabled",
        "Defender potentially unwanted app protection policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows Defender",
        "PUAProtection",
        {1},
        "high",
        ["Keep PUA protection enabled unless security policy says otherwise.", "Export Defender policy before mutation."],
    ),
    (
        "privacy.smartscreen-app-install-control.enabled",
        "SmartScreen app install control policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows Defender\SmartScreen",
        "ConfigureAppInstallControlEnabled",
        {1},
        "high",
        ["Treat SmartScreen controls as security-sensitive.", "Do not disable security prompts as privacy cleanup."],
    ),
    (
        "privacy.smartscreen-shell.enabled",
        "Explorer SmartScreen policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\System",
        "ShellSmartScreenLevel",
        {"Warn", "Block"},
        "high",
        ["Treat Explorer SmartScreen as security-sensitive.", "Export Windows System policy before mutation."],
    ),
    (
        "privacy.edge-user-feedback.disabled",
        "Microsoft Edge user feedback policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "UserFeedbackAllowed",
        {0},
        "medium",
        ["Review Edge feedback workflow.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.edge-diagnostic-data.disabled",
        "Microsoft Edge diagnostic data policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "DiagnosticData",
        {0},
        "medium",
        ["Review Edge diagnostic policy ownership.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.edge-component-updates.enabled",
        "Microsoft Edge component updates policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "ComponentUpdatesEnabled",
        {1},
        "high",
        ["Keep browser component updates enabled for security.", "Do not disable security updates as privacy cleanup."],
    ),
    (
        "privacy.edge-background-mode.disabled",
        "Microsoft Edge background mode policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "BackgroundModeEnabled",
        {0},
        "low",
        ["Review Edge startup/background preference.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.edge-startup-boost.disabled",
        "Microsoft Edge startup boost policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "StartupBoostEnabled",
        {0},
        "low",
        ["Review Edge startup performance preference.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.edge-hubs-sidebar.disabled",
        "Microsoft Edge sidebar policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "HubsSidebarEnabled",
        {0},
        "low",
        ["Review Edge sidebar preference.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.edge-collections-services.disabled",
        "Microsoft Edge collections services policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "EdgeCollectionsEnabled",
        {0},
        "low",
        ["Review Edge collections workflow.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.edge-microsoft-editor.disabled",
        "Microsoft Editor in Edge policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "MicrosoftEditorProofingEnabled",
        {0},
        "medium",
        ["Review grammar/spelling cloud assistance expectations.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.edge-microsoft-editor-synonyms.disabled",
        "Microsoft Editor synonyms in Edge policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "MicrosoftEditorSynonymsEnabled",
        {0},
        "medium",
        ["Review writing assistance expectations.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.edge-follow-service.disabled",
        "Microsoft Edge follow service policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "EdgeFollowEnabled",
        {0},
        "low",
        ["Review Edge content-following workflow.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.edge-share-usage-data.disabled",
        "Microsoft Edge usage data sharing policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "UserDataSnapshotRetentionLimit",
        {0},
        "medium",
        ["Review Edge usage-data retention policy.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.office-telemetry-agent.disabled",
        "Office telemetry agent policy",
        "HKCU",
        r"Software\Policies\Microsoft\Office\Common\ClientTelemetry",
        "DisableTelemetry",
        {1},
        "medium",
        ["Review Microsoft Office diagnostics policy.", "Export Office ClientTelemetry policy before mutation."],
    ),
    (
        "privacy.office-feedback.disabled",
        "Office feedback policy",
        "HKCU",
        r"Software\Policies\Microsoft\Office\Common\Feedback",
        "Enabled",
        {0},
        "low",
        ["Review Office feedback workflow.", "Export Office feedback policy before mutation."],
    ),
    (
        "privacy.onedrive-personal-sync.disabled",
        "OneDrive personal sync policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\OneDrive",
        "DisablePersonalSync",
        {1},
        "medium",
        ["Review OneDrive personal account usage.", "Do not remove synced files as privacy cleanup."],
    ),
    (
        "privacy.activity-feed-machine.disabled",
        "Machine activity feed policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\System",
        "EnableActivityFeed",
        {0},
        "medium",
        ["Review Timeline and cross-device activity expectations.", "Export Windows System policy before mutation."],
    ),
    (
        "privacy.activity-feed-user.disabled",
        "User activity feed policy",
        "HKCU",
        r"Software\Policies\Microsoft\Windows\System",
        "EnableActivityFeed",
        {0},
        "medium",
        ["Review user activity history preference.", "Export Windows System user policy before mutation."],
    ),
    (
        "privacy.diagnostics-enhanced-analytics.limited",
        "Enhanced diagnostic analytics limit policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\DataCollection",
        "LimitEnhancedDiagnosticDataWindowsAnalytics",
        {1},
        "medium",
        ["Review Windows Analytics requirements.", "Export the DataCollection policy key before mutation."],
    ),
    (
        "privacy.diagnostics-one-settings-downloads.disabled",
        "Diagnostics OneSettings download policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\DataCollection",
        "DisableOneSettingsDownloads",
        {1},
        "medium",
        ["Review diagnostics configuration requirements.", "Export the DataCollection policy key before mutation."],
    ),
    (
        "privacy.diagnostics-enterprise-auth-proxy.disabled",
        "Enterprise diagnostics auth proxy policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\DataCollection",
        "DisableEnterpriseAuthProxy",
        {1},
        "medium",
        ["Review enterprise diagnostics proxy ownership.", "Export the DataCollection policy key before mutation."],
    ),
    (
        "privacy.telemetry-commercial-data-pipeline.disabled",
        "Commercial data pipeline telemetry policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\DataCollection",
        "AllowCommercialDataPipeline",
        {0},
        "medium",
        ["Review commercial diagnostics policy.", "Export the DataCollection policy key before mutation."],
    ),
    (
        "privacy.telemetry-desktop-analytics-processing.disabled",
        "Desktop Analytics processing policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\DataCollection",
        "DisableDesktopAnalyticsProcessing",
        {1},
        "medium",
        ["Review Desktop Analytics usage.", "Export the DataCollection policy key before mutation."],
    ),
    (
        "privacy.telemetry-windows-analytics.disabled",
        "Windows Analytics data collection policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\DataCollection",
        "AllowTelemetry_PolicyManager",
        {0},
        "medium",
        ["Review analytics policy ownership.", "Export the DataCollection policy key before mutation."],
    ),
    (
        "privacy.feedback-notifications-machine.disabled",
        "Machine feedback notification policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\DataCollection",
        "DoNotShowFeedbackNotifications",
        {1},
        "low",
        ["Review feedback notification policy ownership.", "Export the DataCollection policy key before mutation."],
    ),
    (
        "privacy.ad-id-group-policy.disabled",
        "Advertising ID group policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\AdvertisingInfo",
        "DisabledByGroupPolicy",
        {1},
        "medium",
        ["Review advertising ID policy ownership.", "Export AdvertisingInfo policy before mutation."],
    ),
    (
        "privacy.cloud-content-tailored-experiences.disabled",
        "CloudContent tailored experiences policy",
        "HKCU",
        r"Software\Policies\Microsoft\Windows\CloudContent",
        "DisableTailoredExperiencesWithDiagnosticData",
        {1},
        "medium",
        ["Review tailored experiences preference.", "Export CloudContent policy before mutation."],
    ),
    (
        "privacy.cloud-content-cloud-optimized.disabled",
        "Cloud optimized content policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\CloudContent",
        "DisableCloudOptimizedContent",
        {1},
        "medium",
        ["Review cloud content policy ownership.", "Export CloudContent policy before mutation."],
    ),
    (
        "privacy.cloud-content-consumer-account-state.disabled",
        "Consumer account state content policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\CloudContent",
        "DisableConsumerAccountStateContent",
        {1},
        "medium",
        ["Review Microsoft account content policy.", "Export CloudContent policy before mutation."],
    ),
    (
        "privacy.cloud-content-soft-landing-policy.disabled",
        "CloudContent soft landing policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\CloudContent",
        "DisableSoftLanding",
        {1},
        "low",
        ["Review Windows tips policy ownership.", "Export CloudContent policy before mutation."],
    ),
    (
        "privacy.cloud-content-third-party-suggestions-policy.disabled",
        "CloudContent third-party suggestions policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\CloudContent",
        "DisableThirdPartySuggestions",
        {1},
        "low",
        ["Review third-party suggestion policy ownership.", "Export CloudContent policy before mutation."],
    ),
    (
        "privacy.search-connected-web.disabled",
        "Connected Search web policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\Windows Search",
        "ConnectedSearchUseWeb",
        {0},
        "medium",
        ["Review Windows Search web integration.", "Export Windows Search policy before mutation."],
    ),
    (
        "privacy.search-connected-web-metered.disabled",
        "Connected Search web over metered policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\Windows Search",
        "ConnectedSearchUseWebOverMeteredConnections",
        {0},
        "medium",
        ["Review Search behavior on metered networks.", "Export Windows Search policy before mutation."],
    ),
    (
        "privacy.search-dynamic-box.disabled",
        "Dynamic Search box content policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\SearchSettings",
        "IsDynamicSearchBoxEnabled",
        {0},
        "low",
        ["Review Search box content preference.", "Prefer Settings UI before registry mutation."],
    ),
    (
        "privacy.search-highlights.disabled",
        "Search highlights policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\Windows Search",
        "EnableDynamicContentInWSB",
        {0},
        "low",
        ["Review Search highlights preference.", "Export Windows Search policy before mutation."],
    ),
    (
        "privacy.search-index-encrypted-files.disabled",
        "Encrypted file indexing policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\Windows Search",
        "AllowIndexingEncryptedStoresOrItems",
        {0},
        "high",
        ["Review encrypted content indexing risk.", "Export Windows Search policy before mutation."],
    ),
    (
        "privacy.copilot-machine.disabled",
        "Machine Windows Copilot policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\WindowsCopilot",
        "TurnOffWindowsCopilot",
        {1},
        "medium",
        ["Review Copilot policy ownership.", "Export WindowsCopilot policy before mutation."],
    ),
    (
        "privacy.copilot-taskbar-button.disabled",
        "Copilot taskbar button preference",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced",
        "ShowCopilotButton",
        {0},
        "low",
        ["Review Copilot taskbar preference.", "Prefer Settings UI before registry mutation."],
    ),
    (
        "privacy.recall-machine.disabled",
        "Machine Recall AI data analysis policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\WindowsAI",
        "DisableAIDataAnalysis",
        {1},
        "high",
        ["Review Recall policy ownership.", "Export WindowsAI policy before mutation."],
    ),
    (
        "privacy.widgets-prelaunch.disabled",
        "Widgets prelaunch policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\Dsh",
        "IsPrelaunchEnabled",
        {0},
        "low",
        ["Review Widgets startup behavior.", "Export Dsh preference before mutation."],
    ),
    (
        "privacy.widgets-taskbar.disabled",
        "Widgets taskbar policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced",
        "TaskbarDa",
        {0},
        "low",
        ["Review Widgets taskbar preference.", "Prefer Settings UI before registry mutation."],
    ),
    (
        "privacy.edge-asset-delivery-service.disabled",
        "Microsoft Edge asset delivery service policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "EdgeAssetDeliveryServiceEnabled",
        {0},
        "medium",
        ["Review Edge content service policy.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.edge-do-not-track.enabled",
        "Microsoft Edge Do Not Track policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "ConfigureDoNotTrack",
        {1},
        "low",
        ["Review browser privacy preference.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.edge-recommendations.disabled",
        "Microsoft Edge recommendations policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "ShowRecommendationsEnabled",
        {0},
        "low",
        ["Review Edge recommendations preference.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.edge-web-widget.disabled",
        "Microsoft Edge web widget policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "WebWidgetAllowed",
        {0},
        "low",
        ["Review Edge web widget preference.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.edge-payment-method-query.disabled",
        "Microsoft Edge payment method query policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "PaymentMethodQueryEnabled",
        {0},
        "medium",
        ["Review payment autofill privacy expectations.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.edge-tab-services.disabled",
        "Microsoft Edge tab services policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "TabServicesEnabled",
        {0},
        "low",
        ["Review Edge tab cloud services.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.edge-related-matches-cloud-service.disabled",
        "Microsoft Edge related matches cloud service policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Edge",
        "RelatedMatchesCloudServiceEnabled",
        {0},
        "medium",
        ["Review Edge cloud assistance behavior.", "Export Edge policy before mutation."],
    ),
    (
        "privacy.defender-realtime-monitoring.enabled",
        "Defender real-time monitoring policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection",
        "DisableRealtimeMonitoring",
        {0},
        "high",
        ["Treat Defender real-time monitoring as security-sensitive.", "Do not disable security protection as privacy cleanup."],
    ),
    (
        "privacy.defender-behavior-monitoring.enabled",
        "Defender behavior monitoring policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection",
        "DisableBehaviorMonitoring",
        {0},
        "high",
        ["Treat behavior monitoring as security-sensitive.", "Do not weaken Defender protections as privacy cleanup."],
    ),
    (
        "privacy.defender-script-scanning.enabled",
        "Defender script scanning policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection",
        "DisableScriptScanning",
        {0},
        "high",
        ["Treat script scanning as security-sensitive.", "Do not weaken Defender protections as privacy cleanup."],
    ),
    (
        "privacy.defender-ioav-protection.enabled",
        "Defender downloaded file scanning policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection",
        "DisableIOAVProtection",
        {0},
        "high",
        ["Treat downloaded file scanning as security-sensitive.", "Do not weaken Defender protections as privacy cleanup."],
    ),
    (
        "privacy.defender-network-protection.enabled",
        "Defender network protection policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\Network Protection",
        "EnableNetworkProtection",
        {1, 2},
        "high",
        ["Treat network protection as security-sensitive.", "Review security ownership before any policy change."],
    ),
    (
        "privacy.defender-controlled-folder-access.review",
        "Defender controlled folder access policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\Controlled Folder Access",
        "EnableControlledFolderAccess",
        {1, 2},
        "high",
        ["Treat controlled folder access as security-sensitive.", "Review ransomware protection ownership before any policy change."],
    ),
    (
        "privacy.app-permission-location.disabled",
        "Per-app location access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\location",
        "Value",
        {"Deny"},
        "medium",
        ["Review location-dependent apps.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.app-permission-human-presence.disabled",
        "Human presence access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\humanPresence",
        "Value",
        {"Deny"},
        "medium",
        ["Review presence sensor workflows.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.app-permission-graphics-capture.disabled",
        "Programmatic graphics capture policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\graphicsCaptureProgrammatic",
        "Value",
        {"Deny"},
        "high",
        ["Review screen capture workflows.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.app-permission-graphics-capture-borderless.disabled",
        "Borderless graphics capture policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\graphicsCaptureWithoutBorder",
        "Value",
        {"Deny"},
        "high",
        ["Review screen capture workflows.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.app-permission-voice-activation.disabled",
        "Voice activation access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\voiceActivation",
        "Value",
        {"Deny"},
        "medium",
        ["Review voice activation workflows.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.app-permission-phone-line-transport.disabled",
        "Phone line transport access policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\phoneLineTransport",
        "Value",
        {"Deny"},
        "medium",
        ["Review phone integration workflows.", "Use Windows Privacy settings where possible."],
    ),
    (
        "privacy.location-scripting.disabled",
        "Location scripting policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\LocationAndSensors",
        "DisableLocationScripting",
        {1},
        "medium",
        ["Review location scripting dependencies.", "Export LocationAndSensors policy before mutation."],
    ),
    (
        "privacy.sensors.disabled",
        "Sensor platform policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\LocationAndSensors",
        "DisableSensors",
        {1},
        "medium",
        ["Review device sensor dependencies.", "Export LocationAndSensors policy before mutation."],
    ),
    (
        "privacy.windows-location-provider.disabled",
        "Windows location provider policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\Windows\LocationAndSensors",
        "DisableWindowsLocationProvider",
        {1},
        "medium",
        ["Review Windows location provider dependencies.", "Export LocationAndSensors policy before mutation."],
    ),
    (
        "privacy.experiments-policy-manager.disabled",
        "PolicyManager experimentation policy",
        "HKLM",
        r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection",
        "AllowExperimentation",
        {0},
        "medium",
        ["Review feature experimentation policy.", "Export DataCollection policy before mutation."],
    ),
    (
        "privacy.store-auto-download.disabled",
        "Microsoft Store automatic download policy",
        "HKLM",
        r"SOFTWARE\Policies\Microsoft\WindowsStore",
        "AutoDownload",
        {2},
        "medium",
        ["Review Store app update workflow.", "Do not disable security updates as privacy cleanup."],
    ),
    (
        "privacy.office-connected-experiences.disabled",
        "Office connected experiences policy",
        "HKCU",
        r"Software\Policies\Microsoft\Office\16.0\Common\Privacy",
        "DisconnectedState",
        {2},
        "medium",
        ["Review Office connected experiences usage.", "Export Office privacy policy before mutation."],
    ),
    (
        "privacy.office-optional-connected-experiences.disabled",
        "Office optional connected experiences policy",
        "HKCU",
        r"Software\Policies\Microsoft\Office\16.0\Common\Privacy",
        "ControllerConnectedServicesEnabled",
        {0},
        "medium",
        ["Review Office optional services usage.", "Export Office privacy policy before mutation."],
    ),
    (
        "privacy.sync-provider-notifications.disabled",
        "Explorer sync provider notification policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced",
        "ShowSyncProviderNotifications",
        {0},
        "low",
        ["Review Explorer sync provider notification preference.", "Prefer Settings UI before registry mutation."],
    ),
    (
        "privacy.windows-chat-taskbar.disabled",
        "Windows Chat taskbar policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced",
        "TaskbarMn",
        {0},
        "low",
        ["Review Windows Chat taskbar preference.", "Prefer Settings UI before registry mutation."],
    ),
    (
        "privacy.windows-people-taskbar.disabled",
        "People taskbar policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\People",
        "PeopleBand",
        {0},
        "low",
        ["Review People taskbar preference.", "Prefer Settings UI before registry mutation."],
    ),
    (
        "privacy.news-interests-taskbar.disabled",
        "News and interests taskbar policy",
        "HKCU",
        r"Software\Microsoft\Windows\CurrentVersion\Feeds",
        "ShellFeedsTaskbarViewMode",
        {2},
        "low",
        ["Review News and interests taskbar preference.", "Prefer Settings UI before registry mutation."],
    ),
)

_APPX_REVIEW_TOKENS: tuple[tuple[str, str, str], ...] = (
    ("bing", "search-and-content", "Bundled Bing/content package; review user workflow before removal."),
    ("clipchamp", "consumer-media", "Consumer media package; review creative workflow before removal."),
    ("copilot", "ai-assistant", "AI assistant package; review policy and Windows feature dependencies."),
    ("feedbackhub", "diagnostics-feedback", "Feedback Hub package; review support and diagnostics needs."),
    ("gethelp", "support", "Support package; review helpdesk/support expectations."),
    ("getstarted", "onboarding", "Onboarding package; usually low value after initial setup but still needs review."),
    ("mixedreality", "mixed-reality", "Mixed Reality package; review device and headset requirements."),
    ("officehub", "office-promo", "Office hub package; review Microsoft 365 workflow."),
    ("people", "contacts", "People/contact package; review mail/contact integration."),
    ("skype", "communications", "Communications package; review user communication workflow."),
    ("solitaire", "games", "Game package; review user preference before removal."),
    ("teams", "communications", "Teams package; review work/school account dependencies."),
    ("windowscommunicationsapps", "mail-calendar", "Mail and Calendar package; review email/calendar usage."),
    ("xbox", "gaming", "Xbox package; review Game Bar, gaming, and controller dependencies."),
    ("yourphone", "phone-link", "Phone Link package; review mobile integration workflow."),
    ("zune", "media", "Legacy media package; review music/video workflow."),
)


def _registry_value(root_name: str, subkey_path: str, value_name: str, *, raw_values: Mapping[str, Any] | None = None) -> tuple[Any | None, dict[str, Any]]:
    key = rf"{root_name}\{subkey_path}\{value_name}"
    if raw_values is not None:
        return raw_values.get(key), source_status("registry-fixture", available=True, reason="test-fixture", evidence={"key": key})
    if os.name != "nt":
        return None, source_status("registry-privacy-policy", available=False, reason="not-windows", evidence={"key": key, "os_name": os.name})
    try:
        import winreg as _winreg  # type: ignore[import-not-found]
    except ImportError:
        return None, source_status("registry-privacy-policy", available=False, reason="winreg-unavailable", evidence={"key": key})
    winreg: Any = _winreg
    hives = {"HKLM": winreg.HKEY_LOCAL_MACHINE, "HKCU": winreg.HKEY_CURRENT_USER}
    hive = hives.get(root_name)
    if hive is None:
        return None, source_status("registry-privacy-policy", available=False, reason="unsupported-hive", evidence={"key": key})
    try:
        with winreg.OpenKey(hive, subkey_path, 0, winreg.KEY_READ) as registry_key:
            value, _value_type = winreg.QueryValueEx(registry_key, value_name)
            return value, source_status("registry-privacy-policy", available=True, reason="registry-value-read", evidence={"key": key})
    except OSError as exc:
        return None, source_status("registry-privacy-policy", available=False, reason="registry-value-unavailable", evidence={"key": key, "error": str(exc)})


def _policy_finding(
    finding_id: str,
    *,
    title: str,
    root_name: str,
    subkey_path: str,
    value_name: str,
    expected_private_values: Iterable[Any],
    observed_value: Any | None,
    risk: str,
    review_steps: list[str],
) -> dict[str, Any]:
    private_values = {str(value) for value in expected_private_values}
    observed = "" if observed_value is None else str(observed_value)
    if observed_value is None:
        state = "not-observed"
    elif observed in private_values:
        state = "privacy-hardened"
    else:
        state = "review-recommended"
    return {
        "id": finding_id,
        "title": title,
        "kind": "registry-policy",
        "risk": risk,
        "state": state,
        "registry_value": rf"{root_name}\{subkey_path}\{value_name}",
        "observed_value": observed,
        "expected_private_values": sorted(private_values),
        "change_evidence": {
            "schema": "cleanwin.registry-privacy-evidence.v1",
            "hive": root_name,
            "subkey_path": subkey_path,
            "value_name": value_name,
            "observed_value": observed,
            "expected_private_values": sorted(private_values),
            "exact_registry_value": rf"{root_name}\{subkey_path}\{value_name}",
            "required_export_command": ["reg.exe", "export", rf"{root_name}\{subkey_path}", "<export-file.reg>", "/y"],
            "rollback_metadata_required": ["hive", "subkey_path", "value_name", "previous_value", "registry_export_ref"],
        },
        "safe_to_execute": False,
        "review_steps": review_steps,
    }


def _appx_inventory_source(raw_appx_packages: Iterable[Mapping[str, Any]] | None) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    if raw_appx_packages is None:
        return [], source_status("appx-packages", available=False, reason="external-command-not-executed", evidence={"command": "Get-AppxPackage -AllUsers"})
    packages = [
        {
            "name": str(package.get("Name") or package.get("name") or ""),
            "package_family_name": str(package.get("PackageFamilyName") or package.get("package_family_name") or ""),
            "publisher": str(package.get("Publisher") or package.get("publisher") or ""),
            "version": str(package.get("Version") or package.get("version") or ""),
            "install_location": str(package.get("InstallLocation") or package.get("install_location") or ""),
        }
        for package in raw_appx_packages
    ]
    return [package for package in packages if package["name"]], source_status("appx-packages", available=True, reason="test-fixture")


def _appx_review_metadata(package_name: str) -> dict[str, str] | None:
    normalized = package_name.lower()
    for token, category, rationale in _APPX_REVIEW_TOKENS:
        if token in normalized:
            return {"matched_token": token, "category": category, "rationale": rationale}
    return None


def _oem_locations(env: Mapping[str, str]) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    candidates = [
        ("programdata-oem", Path(env["PROGRAMDATA"]) / "OEM") if env.get("PROGRAMDATA") else None,
        ("programfiles-oem", Path(env["PROGRAMFILES"]) / "OEM") if env.get("PROGRAMFILES") else None,
        ("programfiles-supportassist", Path(env["PROGRAMFILES"]) / "Dell" / "SupportAssistAgent") if env.get("PROGRAMFILES") else None,
        ("programfiles-hp", Path(env["PROGRAMFILES"]) / "HP") if env.get("PROGRAMFILES") else None,
        ("programfiles-lenovo", Path(env["PROGRAMFILES"]) / "Lenovo") if env.get("PROGRAMFILES") else None,
    ]
    findings: list[dict[str, Any]] = []
    sources: list[dict[str, Any]] = []
    for item in candidates:
        if item is None:
            continue
        source_id, path = item
        exists = path.exists()
        sources.append(source_status(source_id, available=exists, reason="path-present" if exists else "path-missing", evidence={"path": str(path)}))
        if exists:
            findings.append(
                {
                    "id": f"oem-location.{source_id}",
                    "title": f"OEM support location present: {path.name}",
                    "kind": "oem-app-location",
                    "risk": "medium",
                    "state": "review-recommended",
                    "path": str(path),
                    "safe_to_execute": False,
                    "review_steps": ["Review publisher and installed app identity.", "Prefer Settings > Apps or vendor uninstallers.", "Do not delete OEM support directories directly."],
                }
            )
    return findings, sources


def debloat_privacy_report(
    *,
    raw_registry_values: Mapping[str, Any] | None = None,
    raw_appx_packages: Iterable[Mapping[str, Any]] | None = None,
    env: Mapping[str, str] | None = None,
) -> dict[str, Any]:
    current_env = get_env(env)
    sources: list[dict[str, Any]] = []
    findings: list[dict[str, Any]] = []
    for spec in _POLICY_SPECS:
        finding_id, title, root_name, subkey_path, value_name, private_values, risk, review_steps = spec
        value, source = _registry_value(root_name, subkey_path, value_name, raw_values=raw_registry_values)
        sources.append(source)
        findings.append(
            _policy_finding(
                finding_id,
                title=title,
                root_name=root_name,
                subkey_path=subkey_path,
                value_name=value_name,
                expected_private_values=private_values,
                observed_value=value,
                risk=risk,
                review_steps=review_steps,
            )
        )
    appx_packages, appx_source = _appx_inventory_source(raw_appx_packages)
    sources.append(appx_source)
    appx_review: list[tuple[dict[str, Any], dict[str, str]]] = []
    for package in appx_packages:
        metadata = _appx_review_metadata(package["name"])
        if metadata is not None:
            appx_review.append((package, metadata))
    for package, metadata in appx_review:
        findings.append(
            {
                "id": f"appx.review.{package['name']}",
                "title": f"AppX package requires debloat review: {package['name']}",
                "kind": "appx-package",
                "risk": "medium",
                "state": "review-recommended",
                "package": package,
                "review_category": metadata["category"],
                "matched_token": metadata["matched_token"],
                "review_rationale": metadata["rationale"],
                "safe_to_execute": False,
                "review_steps": ["Confirm the package is not required by the user.", "Create recovery evidence before any future AppX removal.", "Prefer documented Windows package management workflows."],
            }
        )
    oem_findings, oem_sources = _oem_locations(current_env)
    sources.extend(oem_sources)
    findings.extend(oem_findings)
    return {
        "schema": DEBLOAT_PRIVACY_REPORT_SCHEMA,
        "destructive": False,
        "dry_run": True,
        "executes_system_commands": False,
        "platform": {"os_name": os.name, "platform": platform.platform(), "is_windows": os.name == "nt"},
        "sources": sources,
        "findings": findings,
        "summary": {
            "finding_count": len(findings),
            "registry_policy_count": len(_POLICY_SPECS),
            "review_recommended_count": sum(1 for finding in findings if finding["state"] == "review-recommended"),
            "privacy_hardened_count": sum(1 for finding in findings if finding["state"] == "privacy-hardened"),
            "appx_review_count": len(appx_review),
            "oem_location_count": len(oem_findings),
        },
        "execution_gate": {
            "system_execution_enabled": False,
            "requires_restore_point": True,
            "requires_registry_export": True,
            "requires_appx_inventory_snapshot": True,
            "ai_auto_call_allowed": False,
        },
        "non_goals": [
            "This report does not remove AppX packages.",
            "This report does not change privacy, telemetry, Copilot, Recall, or consumer feature policy keys.",
            "This report does not delete OEM application directories.",
            "This report does not execute PowerShell, DISM, winget, or vendor uninstallers.",
        ],
    }
